# Generated by Django 3.0.8 on 2020-07-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='guestEmail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='guestIsDrinking',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('isDrinking', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='api.Employee')),
            ],
        ),
    ]
