# Generated by Django 3.0.8 on 2020-07-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200729_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='employee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='api.Employee'),
        ),
    ]
